default_tree := "main.jj"

help:
  @just -l

ccache +args:
  CCACHE_CONFIGPATH=$(realpath ccache.conf) ccache {{args}}

ccache-watch wait='5':
  while true; do clear; just ccache -s; sleep {{wait}}; done

clone:
  if [ ! -d main.jj ]; then jj git clone --colocate https://github.com/freebsd/freebsd-src.git main.jj; fi

bootstrap tree=default_tree:
  ./scripts/build.sh bootstrap {{tree}}

build tree=default_tree:
  ./scripts/build.sh build {{tree}}

clean tree=default_tree:
  ./scripts/build.sh clean {{tree}}

release tree=default_tree:
  ./scripts/build.sh release {{tree}}

clean-release tree="main.jj":
  ./scripts/build.sh clean-release {{tree}}

[no-cd]
format-patch change="":
  #!/bin/sh
  set -eu
  commit=$(jj -R ../../repos/freebsd-src.jj show {{change}} -T 'commit_id ++ "\n"' -s | head -n 1)
  git -C ../../repos/freebsd-src.jj format-patch -o $(pwd)/patches -U99999 ${commit}^..${commit}
