[user]
name = "Pat Maddox"
email = "pat@patmaddox.com"

[revset-aliases]
"context()" = "context(@)"
"context(r)" = "heads(::r & ::trunk())::r | r:: | trunk() | (::r & mutable())"
"jj_default()" = "jj_default(@)"
"jj_default(r)" = "present(r) | ancestors(immutable_heads().., 2) | trunk()"
"tree()" = "context() | jj_default()"
"wip()" = "(tracked_remote_bookmarks():: ~ ::tracked_remote_bookmarks()) | tracked_remote_bookmarks()"

[aliases]
gp = ["git", "push", "--tracked"]
l = ["log", "-r", "fork_point(::trunk() | ::@)::@", "--no-graph"]
tree = ["log", "-r", "tree()"]
wip = ["log", "-r", "wip()"]

[revsets]
log = "context()"

[templates]
git_push_bookmark = '"patmaddox/" ++ change_id.short()'

[signing]
backend = "ssh"
behavior = "keep"
key = "~/lab/default.jj/.pubkeys/patmaddox-beastie.pub"

[signing.backends.ssh]
allowed-signers = "~/lab/default.jj/.pubkeys/allowed_signers"
program = "/usr/bin/ssh-keygen"

[ui]
show-cryptographic-signatures = true

[git]
fetch = ["glob:*"]

[[--scope]]
--when.repositories = ["~/evirts"]
[--scope.user]
email = "pat@evirts.com"
