subinclude("//build_defs:fetch_repos")

fetch_repos([{
        "name": "freebsd-ports",
        "repo": "git@github.com:patmaddox/freebsd-ports.git",
        "remotes": [{
            "name": "upstream",
            "url": "https://github.com/freebsd/freebsd-ports.git"
        }]
}])
