ninja_root := `jj root`
ninja := "ninja -C " + ninja_root
src_root := "oss/freebsd-src"

help:
  @just -l

# Show ccache status
ccache +args:
  CCACHE_CONFIGPATH=$(realpath ccache.conf) ccache {{args}}

# Refresh ccache stats every {wait} seconds
ccache-watch wait='5':
  while true; do clear; just ccache -s; sleep {{wait}}; done

# Clone the git repository
clone:
  if [ ! -d main.jj ]; then jj git clone --colocate https://github.com/freebsd/freebsd-src.git main.jj; fi

# Run `make buildworld` for the given config
buildworld config:
  {{ninja}} ninja-out/{{src_root}}/{{config}}/buildworld.stamp

# Run `make buildkernel` for the given config
buildkernel config:
  {{ninja}} ninja-out/{{src_root}}/{{config}}/buildkernel.stamp

# Run `make packages` for the given config
pkgbase config:
  {{ninja}} ninja-out/{{src_root}}/{{config}}/pkgbase.stamp

# Run `make vm-image` for the given config
vm-image config:
  {{ninja}} ninja-out/{{src_root}}/{{config}}/vm-image.stamp

[no-cd]
format-patch change="":
  #!/bin/sh
  set -eu
  commit=$(jj -R ../../repos/freebsd-src.jj show {{change}} -T 'commit_id ++ "\n"' -s | head -n 1)
  git -C ../../repos/freebsd-src.jj format-patch -o $(pwd)/patches -U99999 ${commit}^..${commit}
