help:
  @just -l

# Show ccache status
ccache +args:
  CCACHE_CONFIGPATH=$(realpath ccache.conf) ccache {{args}}

# Refresh ccache stats every {wait} seconds
ccache-watch wait='5':
  while true; do clear; just ccache -s; sleep {{wait}}; done

# Clone the git repository
clone:
  if [ ! -d main.jj ]; then jj git clone --colocate https://github.com/freebsd/freebsd-src.git main.jj; fi

# Enter a build environment shell (run from a target dir)
[no-cd]
buildenv:
  {{justfile_directory()}}/share/buildenv.sh

[no-cd]
format-patch change="":
  #!/bin/sh
  set -eu
  commit=$(jj -R ../../repos/freebsd-src.jj show {{change}} -T 'commit_id ++ "\n"' -s | head -n 1)
  git -C ../../repos/freebsd-src.jj format-patch -o $(pwd)/patches -U99999 ${commit}^..${commit}
