# https://klarasystems.com/articles/evaluating-freebsd-current-for-production-use/
# requires GENERIC-NODEBUG kernel for CURRENT
WITH_MALLOC_PRODUCTION="YES"
WITHOUT_LLVM_ASSERTIONS="YES"

WITH_CCACHE_BUILD="YES"

WITHOUT_LIB32="YES"
WITHOUT_DEBUG_FILES="YES"

WITH_REPRODUCIBLE_BUILD="YES"
WITHOUT_QEMU="YES" # -DNO_ROOT fails if this is not set
