# Build and install sync-pw to ninja-out/bin
build:
    ninja -C ../.. bin.sync-pw

# Run tests
test:
    doas kyua test

# Build and test
check: build test

# Clean build artifacts
clean:
    rm -rf _build
    ninja -C ../.. -t clean bin.sync-pw