subinclude("//build_defs:repos")

fetch_repos([
    {
        "name": "freebsd-ports",
        "url": "git@github.com:patmaddox/freebsd-ports.git",
        "remotes": [{
            "name": "upstream",
            "url": "https://github.com/freebsd/freebsd-ports.git",
        }],
    },
    {"name": "jj", "url": "https://github.com/martinvonz/jj.git"},
    {"name": "please", "url": "https://github.com/thought-machine/please.git"}
])
