global
	daemon
defaults
	mode http
	timeout connect 5000ms
	timeout client 50000ms
	timeout server 50000ms

frontend patmaddox.com
	bind 45.32.226.152:80
	bind 45.32.226.152:443 ssl crt /root/www_patmaddox_com.haproxy.pem
	http-request redirect scheme https unless { ssl_fc }
	redirect prefix https://patmaddox.com code 301 unless { hdr(host) -i patmaddox.com }
	option forwardfor
	default_backend fossil

backend fossil
	server server1 127.0.0.1:8080
