remotes [
  {name: "upstream", src: "https://github.com/allanjude/uclcmd.git"},
  {name: "gh-pm", src: "git@github.com:patmaddox/uclcmd.git"}
]

workspaces [
  {name: "default", bookmark: "master", remote: "upstream"},
  {name: "man-page"}
]

push_repo = "gh-pm"
