* TODO The Isolation Trap - erlang isolation concurrency limits  :erlang:otp:
What Erlang shows about the limits of concurrency through isolation
https://causality.blog/essays/the-isolation-trap/
* TODO Larry Wall three great virtues of a programmer
https://threevirtues.dev/

According to Larry Wall, the original author of the Perl programming
language, there are three great virtues of a programmer; Laziness,
Impatience and Hubris

Laziness: The quality that makes you go to great effort to reduce
overall energy expenditure. It makes you write labor-saving programs
that other people will find useful and document what you wrote so you
don't have to answer so many questions about it.

Impatience: The anger you feel when the computer is being lazy. This
makes you write programs that don't just react to your needs, but
actually anticipate them. Or at least pretend to.

Hubris: The quality that makes you write (and maintain) programs that
other people won't want to say bad things about.

Reference: The Three Virtues (Wayback Machine) | Source code:
dAnjou/enumerations.three_virtues
