help:
  just -l

test:
  kyua test

demo:
  #!/bin/sh
  set -eu
  tmpdir=$(mktemp -d -t emacs-dev)/.emacs
  echo "emacs tmpdir is ${tmpdir}"
  make -s install DESTDIR=${tmpdir}
  emacs --init-directory=${tmpdir}

# Install to .emacs.dev
install-dev:
  rm -rf $HOME/.emacs.dev
  make -s 2>/dev/null
  make -s install DESTDIR=$HOME/.emacs.dev
