help:
  just -l

pkg:
  redo-ifchange patmaddox-emacs.pkg

test: pkg
  kyua test

install: pkg
  INSTALL_AS_USER=yes pkg -r ~ install -U $(realpath patmaddox-emacs.pkg)

demo file="": pkg
  #!/bin/sh
  set -eu
  tmpdir=$(mktemp -d -t emacs-dev)
  echo "emacs tmpdir is ${tmpdir}"
  INSTALL_AS_USER=yes pkg -r ${tmpdir} add $(realpath patmaddox-emacs.pkg)
  emacs --init-directory=${tmpdir}/.emacs.d {{file}}
