baseURL = 'https://patmaddox.com'
locale = 'en-us'
title = 'I am Pat Maddox'

disablePathToLower = true

[module]
[[module.imports]]
  path = 'github.com/alex-shpak/hugo-book'
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = '../../doc/zib'
  target = 'content/zib'

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'base16-snazzy'

[params]
  BookSection = '/'
  BookToC = true
  BookSearch = true
