newbe_src := "../../../src/new-be"
freebsd_src := "../../../src/freebsd-src"
release := "releng-14.2"

help:
  just -l

# Create a new, fully-configured boot environment
new-be name:
  packages="{{freebsd_src}}/_build/{{release}}/amd64.amd64/release"; \
  {{newbe_src}}/new-be gulliver.conf

# Import any dist files that have been edited on the local system
import-config:
  {{newbe_src}}/import-config dist/base.mtree dist/packages.mtree

# Update portsfile with list of manually-installed ports
update-ports:
  {{newbe_src}}/list-ports | tee $(hostname -s).ports
