subinclude("//build/defs:repos")

fetch_jj_cmd(
    name = "fetch",
    repo = "jj",
    url = "https://github.com/martinvonz/jj.git"
)

jj_repo(
    name = "repo--v0.23.0",
    repo = "jj",
    version = "v0.23.0"
)
