set -g mouse off

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set -g mode-keys vi
set -g status-keys vi

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -c "#{pane_current_path}"

# bind X confirm-before -p "kill-window #W? (y/n)" kill-window
bind X kill-window
