#!/bin/sh
set -eu
set -o pipefail

built=""
cur_target=""
deps_dir=${TMPDIR:-/tmp}/ss/$(pwd)
outdir=""
targets=""
visited=""

target() {
	local t
	t=${1}; shift
	cur_target="${t}"
	targets="${targets} ${t}"
	set_build_function ${t} ${1:-${t}}
}

stamp() {
	target "${@}"
	eval "__stamp_$(sanitize_target "${cur_target}")=1"
}

is_stamp() {
	local val
	eval "val=\${__stamp_$(sanitize_target "${1}"):-0}"
	[ "${val}" = "1" ]
}

mark_visited() {
	eval "__visited_$(sanitize_target ${1})=1"
	visited="${visited} ${1}"
}

is_visited() {
	local val
	eval "val=\${__visited_$(sanitize_target ${1}):-0}"
	[ "${val}" = "1" ]
}

out-of-tree() {
	eval "__oot_$(sanitize_target "${cur_target}")=1"
}

is_oot() {
	local val
	eval "val=\${__oot_$(sanitize_target "${1}"):-0}"
	[ "${val}" = "1" ]
}

is_opt_outdir() {
	[ -n "${outdir}" ]
}

resolve_path() {
	if is_opt_outdir && is_oot "${1}"; then
		echo "${outdir}/${1}"
	else
		echo "${1}"
	fi
}

needs() {
	add_deps "${cur_target}" "${@}"
}

add_deps() {
	local t which_deps d
	t=${1}; shift
	which_deps="exp"
	t=$(sanitize_target "${t}")
	for d in "${@}"; do
		if [ "${d}" = ":" ]; then
			which_deps="imp"
			continue
		fi
		eval "__${which_deps}_deps_${t}=\"$(get_deps ${which_deps} ${t}) ${d}\""
	done
}

get_deps() {
	local which_deps t deps
	which_deps=${1}; shift
	t=${1}; shift
	t=$(sanitize_target "${t}")
	eval "deps=\${__${which_deps}_deps_${t}:-}"
	echo "${deps}"
}

sanitize_target() {
	case "$1" in
		*[.:/\-]*) echo "${1}" | sed -e "s/\./__DOT__/g" -e "s/:/__COLON__/g" -e "s|/|__SLASH__|g" -e "s/-/__DASH__/g" ;;
		*) echo "$1" ;;
	esac
}

set_build_function() {
	eval "__build_$(sanitize_target ${1})=${2}"
}

get_build_function() {
	local _fn
	eval "_fn=\${__build_$(sanitize_target ${1}):-}"
	echo "$_fn"
}

write_depsum() {
	mkdir -p "$(dirname "${2}")"
	md5 -q "${1}" > "${2}"
}

any_is_ood() {
	local t
	for t in "${@}"; do
		if is_ood ${t}; then return 0; fi
	done
	return 1
}

is_ood() {
	local t p
	t=${1}
	p=$(resolve_path ${t})
	if [ ! -f ${p} ]; then return 0; fi

	write_depsum ${p} ${deps_dir}/${t}.new

	local sum_file
	sum_file=${deps_dir}/${t}
	if [ ! -f ${sum_file} ]; then return 0; fi

	! cmp -s ${sum_file} ${deps_dir}/${t}.new
}

build_targets() {
	local target
	for target in ${targets}; do
		maybe_build ${target}
	done
	for target in $(echo ${built} | tr ' ' '\n' | sort -u); do
		local p
		p=$(resolve_path ${target})
		if [ -f ${deps_dir}/${target}.new ]; then
			mv ${deps_dir}/${target}.new ${deps_dir}/${target}
		elif [ -f ${p} ]; then
			write_depsum ${p} ${deps_dir}/${target}
		fi
	done
}

maybe_build() {
	local target exp_deps imp_deps
	target=${1}; shift

	if is_visited ${target}; then return 0; fi
	mark_visited ${target}

	exp_deps=$(get_deps exp ${target})
	imp_deps=$(get_deps imp ${target})

	if [ -n "${exp_deps}" ] || [ -n "${imp_deps}" ]; then
		local d
		for d in ${exp_deps} ${imp_deps}; do
			maybe_build ${d}
		done
	fi

	local build_fn deps
	build_fn=$(get_build_function ${target})

	if [ -n "${build_fn}" ] && { is_stamp ${target} || any_is_ood ${target} ${exp_deps} ${imp_deps}; }; then
		echo ${target} >&2
		local _d
		deps=""
		for _d in ${exp_deps}; do
			deps="${deps} $(resolve_path ${_d})"
		done
		local _orig_target
		_orig_target=${target}
		target=$(resolve_path ${target})
		mkdir -p "$(dirname "${target}")"
		${build_fn}
		target=${_orig_target}
		built="${built} ${target} ${exp_deps} ${imp_deps}"
	fi
}

mkdir -p ${deps_dir}

while getopts "o:" _opt; do
	case ${_opt} in
		o) outdir=${OPTARG} ;;
	esac
done
shift $((OPTIND - 1))

if [ $# -gt 0 ] && [ "${1}" = "help" ]; then
	echo "usage: ss ls"
	echo "       ss [-o outdir] [target]"
	exit 0
fi

if [ $# -gt 0 ] && [ "${1}" = "ls" ]; then
	. ./all.ss
	echo "${targets}" | tr ' ' '\n' | grep .
	exit 0
fi

if [ $# -eq 0 ]; then
	. ./all.ss
else
	_need_all=false
	for _arg in "${@}"; do
		if [ -f "./${_arg}.ss" ]; then
			. ./${_arg}.ss
		else
			_need_all=true
		fi
	done
	if ${_need_all}; then
		. ./all.ss
	fi
	targets="${@}"
fi
build_targets
