#!/bin/sh
set -eu
set -o pipefail

targets=""
deps_dir=${TMPDIR}/ss
cur_target=""

target() {
	local t
	t=${1}; shift
	cur_target="${t}"
	targets="${t} ${targets}"
	set_build_function ${t} ${1:-${t}}
}

needs() {
	add_deps "${cur_target}" "${@}"
}

add_deps() {
	local t
	t=${1}; shift
	t=$(sanitize_target "${t}")
	eval "__deps_${t}=\"$(get_deps ${t}) ${@}\""
}

get_deps() {
	local t deps
	t=${1}; shift
	t=$(sanitize_target "${t}")
	eval "deps=\${__deps_${t}:-}"
	echo "${deps}"
}

sanitize_target() {
	echo "${1}" | sed -e "s/\./__DOT__/g"
}

set_build_function() {
	eval "__build_$(sanitize_target ${1})=${2}"
}

get_build_function() {
	local _fn
	eval "_fn=\${__build_$(sanitize_target ${1}):-}"
	echo "$_fn"
}

write_depsum() {
	mkdir -p "$(dirname "${2}")"
	md5 -q "${1}" > "${2}"
}

any_is_ood() {
	local t
	for t in "${@}"; do
		if is_ood ${t}; then return 0; fi
	done
	return 1
}

is_ood() {
	local t
	t=${1}
	if [ ! -f ${t} ]; then return 0; fi

	local sum_file
	sum_file=${deps_dir}/${t}
	if [ ! -f ${sum_file} ]; then return 0; fi

	[ "$(md5 -q ${t})" != "$(cat ${sum_file})" ]
}

build_targets() {
	local target
	for target in ${targets}; do
		maybe_build ${target}
	done
}

maybe_build() {
	local target deps
	target=${1}; shift
	deps=$(get_deps ${target})

	if [ -n "${deps}" ]; then
		local d
		for d in ${deps}; do
			maybe_build ${d}
		done
	fi

	local build_fn
	build_fn=$(get_build_function ${target})
	if [ -n "${build_fn}" ] && any_is_ood ${target} ${deps}; then
		echo ${target} >&2
		${build_fn}

		for t in ${target} ${deps}; do
			write_depsum ${t} ${deps_dir}/${t}
		done
	fi
}

mkdir -p ${deps_dir}
. all.ss
build_targets
