help:
  @just -l

# list installed port origins
list-ports:
  sh scripts/list-ports.sh

# run `make index` on default.jj
index:
  PORTSDIR=$(realpath default.jj) make -C default.jj index

[no-cd]
lint:
  #!/bin/sh
  portclippy Makefile
  portfmt -i Makefile
  PORTSDIR=$(git rev-parse --show-toplevel) portlint -A

# run poudriere testport on all unmerged commits
test-pending:
  sh scripts/test-pending.sh $(realpath ../../repos/freebsd-ports.jj)

clone:
  if [ ! -d ../../repos/freebsd-ports.jj ]; then jj git clone git@github.com:patmaddox/freebsd-ports.git ../../repos/freebsd-ports.jj; fi
  jj -R ../../repos/freebsd-ports.jj git remote add upstream https://github.com/freebsd/freebsd-ports.git 2>&1 || true

testport *args:
  doas poudriere testport -j 142 -p dev {{args}}

[no-cd]
format-patch jjid:
  jj log -r {{jjid}} --no-graph -T 'commit_id ++ "\n"' | \
    xargs -I {} git format-patch -1 -C 99999 --stdout {} | \
    grep -v '^Change-Id: I'
